### ISSUE TITLE
Feedback Sprint 1 Datadashboard 

### ISSUE THREAD

**Issue by nerdale** [AngieMonroe/cdmx-2018-06-bc-core-am-data-dashboard#10]
Hola @marfloresrayon y @AngieMonroe 
He estado revisando el proyecto y tengo algunos comentarios :smile:

1. Excelente indentación, las felicito, está todo el código muy ordenado y limpio, totalmente comprensible para cualquier persona que externa que desee hacerles codereview y/o feedback :clap: 

2. Ya acceden a la data,  deben comenzar a jugar más para poder acceder a los datos que deben imprimir en el datadashboard y para los cálculos que deberán hacer :rocket: 

3.Ojo con el trabajo colaborativo, veo solo dos commits de @marfloresrayon todos los demás corresponden a @AngieMonroe , recuerden mantener los repositorios lo más actualizado posible (ambos, tanto el fork master como el colaborativo)

4. Felicitaciones por todo el trabajo UX que hay detrás, adjuntan todo lo solicitado, eso si en figma solo veo una pantalla, les aconsejo revisar que sucede ahí.

5. No se olviden de desarrollar siempre observando y probando los tests. 

Ánimo y en honor al tiempo comiencen luego con a darle forma final y toda la funcionalidad al datadashboard :rocket:

**Comment by ghost** [comment]
Hola @nerdale hemos actualizado los repositorios y corregido las ligas de Figma. Seguimos trabajando en el acceso a la data y probando los tests.

Agradecemos tus comentarios, nos ayudan mucho 👍

**Comment by nerdale** [comment]
Daré por cerrado el issue :smile: 
:rocket: 

(felicitaciones por los issues y milestones)
