### ISSUE TITLE
Terminar objeto de la primera función.

### ISSUE THREAD

**Issue by ghost** [AngieMonroe/cdmx-2018-06-bc-core-am-data-dashboard#25]

**Comment by ghost** [comment]
A partir de haber obtenido la data de las alumnas:
-Indicar dónde se imprimirá la data 
-Indicar cómo imprimiremos la data

**Comment by AngieMonroe** [comment]
Durante los primeros dos sprint se trabajó la data iterandola a partir de los valores que la usuaria seleccionará. Al llegar a los test nos dimos cuenta que necesitábamos una función pura, así que se comenzó a trabajar en ella. Para no desperdiciar la información ya trabajada con esta se decidió comenzar a pintar en pantalla por los tiempos de entrega.
