### ISSUE TITLE
Dinamizar gráficas o cambiarlas por barras de proceso dinámicas.

### ISSUE THREAD

**Issue by ghost** [AngieMonroe/cdmx-2018-06-bc-core-am-data-dashboard#29]

**Comment by ghost** [comment]
-Investigar sobre gráficas dinámicas 
-Investigar sobre progress bar dinámicas
-Probar y practicar
-Implementar lo aprendido

**Comment by AngieMonroe** [comment]
Se implementaron las barras de progreso en la plataforma.
