### ISSUE TITLE
Terminar de traer la data de las alumnas.

### ISSUE THREAD

**Issue by ghost** [AngieMonroe/cdmx-2018-06-bc-core-am-data-dashboard#30]

**Comment by ghost** [comment]
-Investigar cómo armar un objeto a partir de otro objeto
-Practicar y probar en la función 
-Implementar lo aprendido y probado

**Comment by AngieMonroe** [comment]
Se trabajo la primer función de acuerdo a lo solicitado de manera pura. Para no descartar el trabajo que ya se había hecho previamente para iterar en la data y de acuerdo a los tiempos se decidió ocupar esta forma para pintar en pantalla.
