### ISSUE TITLE
Feedback Datadashboard

### ISSUE THREAD

**Issue by nerdale** [AngieMonroe/cdmx-2018-06-bc-core-am-data-dashboard#49]
Queridas @AngieMonroe y @marfloresrayon 
Estuve revisando el proyecto entregado y tengo algunos comentarios:

1. Felicitaciones por el proyecto, se ve un trabajo que aún tiene cosas por resolver, pero en general está bastante completo, hay un buen trabajo no sólo de lógica sino que también de UX, ambos con issues totalmente mejorables. Siento que acá primó un poco más el lema de **Hacer menos pero hacerlo bien** las felicito por eso :clap: 

2. Felicitaciones por el readme, ahora si tenía información, me hubiese gustado que explicaran brevemente el porque de las desiciones de diseño que tomaron, como un preambulo para luego ver el readme directo de ux. De igual manera pueden mejorar el formato del readme, si les interesa pueden revisar este link [sobre formatos en archivos markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

3. Muy bien por configurar linter, pero les quedaron errores/warnings que no resolvieron, lo esencial del linter es poder visibilizar y resolver esos problemas.

4. Si bien los test no pasan, si se nota que en un momento existió orientación a test pero que a medida que el proyecto creció esto se dejó de lado. Algo totalmente mejorable, deben trabajarlo desde ahora ya. :rocket: 

5. En el **css** hay algunos id que tienen las mismas propiedades, las podrían haber agrupados, pero van por buen camino.

6. La separación entre lógica y dom va bien, a veces se pierde pero muy poco.

7. En cuanto a UX hay pequeños detalles de contraste y alineación, hay también pequeños detalles en el responsive como textos que se desbordan del cuadro amarillo por ejemplo. Hay algunos tamaños que faltan manejar mejor para que el tema de la jararquía sea correcto, por ejemplo el número de estudiantes activas es excesivamente grande en comparación con los títulos de los tamaños :smile: 

8. Excelente trabajo colaborativo :clap: se ve manejo de git & github. Felicitaciones!

Vamos con todo para el siguiente proyecto :metal:

**Comment by ghost** [comment]
Vamos con todo Ale! 🚀 Muchas gracias por tus comentarios y tu guía a lo largo de todo el proceso.  Tomaremos todo lo que nos comentas en cuenta para continuar trabajando en incrementos para este proyecto 😄

**Comment by nerdale** [comment]
Vamos con todo chicas! todo el power :muscle:
